import os
import numpy as np


def get_common_parameters(qa_pairs):

    words = set()

    for qa_pair in qa_pairs:
        words.update(qa_pair[1])

    vocab = sorted(list(words))
    word_idx = dict((c, i + 1) for i, c in enumerate(vocab))

    question_size = max([len(qa_pair[1]) for qa_pair in qa_pairs])

    return word_idx, question_size


def load_captions(dataset_dir):
    '''
    grabs all embeddings of captions in .npy files generated by InferSent
    returns a dictionary of the form: {<species_id>: <captions>}
               <species_id> - integer representing the species
               <caption_words> - a numpy matrix of corresponding to embeddings of captions
    '''

    caption_embeddings = {}
    files = [(int(f.split('.')[0]), os.path.join(dataset_dir, f)) for f in os.listdir(dataset_dir)]

    for (species_id, f) in files:
        species_captions = np.load(f)

        caption_embeddings[species_id] = species_captions

    return caption_embeddings
